---
- name: "Ensure other hosts are defined in /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
    state: present
  when: "hostvars[item].ansible_default_ipv4.address is defined and item != ansible_hostname"
  with_items: "{{ groups['all'] | difference(hostsfile_ignore_auto) }}"

- name: "Ensure manually-defined hosts exist in /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item.name }}$'
    line: "{{ hostvars[item.name]['ansible_' + item.interface].ipv4.address}} {{ hostvars[item.name].ansible_hostname }}"
    state: present
  when: "hostvars[item.name].ansible_hostname != ansible_hostname"
  with_items: "{{ hostsfile_manual }}"

- name: "Ensure local host is defined for IPv4"
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.0.1.*'
    line: "127.0.0.1 localhost.localdomain localhost {{ ansible_hostname }}"

- name: "Ensure local host is defined for IPv6"
  lineinfile:
    dest: /etc/hosts
    regexp: '^::1.*'
    line: "::1 localhost.localdomain localhost {{ ansible_hostname }}"
